/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class beast_phylodynamics_ExactBDSIS */

#ifndef _Included_beast_phylodynamics_ExactBDSIS
#define _Included_beast_phylodynamics_ExactBDSIS
#ifdef __cplusplus
extern "C" {
#endif
#undef beast_phylodynamics_ExactBDSIS_SAMPLE_EVENT
#define beast_phylodynamics_ExactBDSIS_SAMPLE_EVENT 0L
#undef beast_phylodynamics_ExactBDSIS_BRANCH_EVENT
#define beast_phylodynamics_ExactBDSIS_BRANCH_EVENT 1L
#undef beast_phylodynamics_ExactBDSIS_SWITCH_EVENT
#define beast_phylodynamics_ExactBDSIS_SWITCH_EVENT 3L
#undef beast_phylodynamics_ExactBDSIS_SURVIVAL
#define beast_phylodynamics_ExactBDSIS_SURVIVAL 99L
/*
 * Class:     beast_phylodynamics_ExactBDSIS
 * Method:    DirtyExpoTree
 * Signature: ([D[D[D[DD[D[IZIZI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_beast_phylodynamics_ExactBDSIS_DirtyExpoTree
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdouble, jdoubleArray, jintArray, jboolean, jint, jboolean, jint);

#ifdef __cplusplus
}
#endif
#endif
